import Head from "next/head"
import Upload from "../components/Upload"
import Stars from "../components/Stars"
import styles from "../styles/Home.module.css"
import { Box, Text } from "@chakra-ui/react"

export default function Home() {
    return (
        <Box className={styles.container} bgColor="#000717" w="100%" h="100vh">
            <Head>
                <title>Sportlight</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Stars id="landing" color="#ffffff" />
            <Upload />
            <Text
                w="100%"
                mt={4}
                textAlign="center"
                fontSize="md"
                fontWeight="semibold"
                color="white">
                Made with 🤍 by The Unknowns
            </Text>
        </Box>
    )
}
