import Head from 'next/head'
import Upload from '../components/Upload'
import styles from '../styles/Home.module.css'
import { Box } from '@chakra-ui/react'

export default function Home() {
  return (
    <Box className={styles.container} bgColor="#ffffff" h="100vh">
      <Head>
        <title>Sportlight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Upload />
    </Box>
  )
}
